//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFactory.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarFactoryEntities : DbContext
    {
        public CarFactoryEntities()
            : base("name=CarFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automobile> Automobiles { get; set; }
        public virtual DbSet<Construction> Constructions { get; set; }
        public virtual DbSet<ConstructionProcess> ConstructionProcesses { get; set; }
        public virtual DbSet<ConstructionStep> ConstructionSteps { get; set; }
        public virtual DbSet<ConstructionStepRequirement> ConstructionStepRequirements { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
    }
}
