//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFactory.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstructionStep()
        {
            this.ConstructionProcesses = new HashSet<ConstructionProcess>();
            this.RolePermissions = new HashSet<RolePermission>();
            this.ConstructionStepRequirements = new HashSet<ConstructionStepRequirement>();
            this.ConstructionStepRequirements1 = new HashSet<ConstructionStepRequirement>();
        }
    
        public int Id { get; set; }
        public int AutomobileId { get; set; }
        public int StepNumber { get; set; }
        public string StepName { get; set; }
    
        public virtual Automobile Automobile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionProcess> ConstructionProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionStepRequirement> ConstructionStepRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionStepRequirement> ConstructionStepRequirements1 { get; set; }
    }
}
