//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFactory.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionStepRequirement
    {
        public int Id { get; set; }
        public int StepId { get; set; }
        public int RequiredStepId { get; set; }
    
        public virtual ConstructionStep ConstructionStep { get; set; }
        public virtual ConstructionStep ConstructionStep1 { get; set; }
    }
}
